apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  selector:
    matchLabels:
      app: full
      tier: back
  template:
    metadata:
      labels:
        app: full
        tier: back
    spec:
      containers:
      - name: back
        image: zunderene/back:v3
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
---

apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  selector:
    app: full
    tier: back
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
---