---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: full
      tier: frontend
  template:
    metadata:
      labels:
        app: full
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image:  zunderene/from:v3
        resources:
          requests:
            cpu: 700m
            memory: 900Mi
        env:
        - name: URL_API
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 3000
---


apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: full
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 4000
  selector:
    app: full
    tier: back
---
kind: Service
apiVersion: v1
metadata:
  name:  salida
spec:
  selector:
    app:  full
    tier: frontend
  type:  LoadBalancer
  ports:
  - name: http
    port:  80
    targetPort:  3000
